#!/usr/bin/env bash
docker run --rm -ti \
    --user $(id -u):$(id -g) \
    --volume ~/.config/configstore:/home/node/.config/configstore \
    --volume ~/.config/npm/lib/node_modules:/home/node/.config/npm/lib/node_modules \
    --volume ~/.config/npm/bin:/home/node/.config/npm/bin \
    --volume ~/.config/npm/cache:/home/node/.config/npm/cache \
    --volume ~/.config/npm/cache:/home/node/.config/npm/share \
    --volume ~/.npmrc:/home/node/.npmrc \
    --volume $(pwd):/app \
    -w /app \
    -e PATH="/home/node/.config/npm/bin:$PATH" \
    node:12.16.1 npm $@
